version: "3.7"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  proxy:
    image: proxy:latest
    ports:
        - 8080:8080
    restart: always